### PR TITLE
Refactor CSS definition #14

### PR DESCRIPTION
**Pull request by dacdao1**
### Motivation

This should help organize and start the process of fixing issues #14 

### Checklist

It passed the testing phase and the program will run smoothly and normally.

### How to test

Use the magic password.
npm run develop

### CODE REVIEW

**Comment by Simply007** [comment]
I have changed the base.

**Comment by Simply007** [comment]
Hello @dacdao1,

I have created [pull request](https://github.com/dacdao1/kentico.github.io/pull/1) to your fork to ensure green CI.

Required changes:
* It would be great to restructure the css like that
```
/src/pages/index.scss importing required css for index page
/src/styles/_mixins.scss (mind the module names should start with the underscore) containing the same as your mixins
/src/styles/_global.scss containg global styles
/src/styles/_responsive.scss containg global responsive styles
/src/components/_heading_section.scss imported in headingSection.js including heading section specific tyles (invl. responsive ones).
```
* I would move the code from `_selector.scss` to the section where it is used right now to the section
** It the code is duplicated use the mixin to share the code

If you have any question feel free to ask! Thanks for helping the OS!

**Comment by Simply007** [comment]
Hello @dacdao1,

I am about to create a new sub-page for the site. Do you have any ETA when you will take a look at the style restructuralization? It is a pre-requisite for the new page.

**Comment by dacdao1** [comment]
Could you give me until the end of Sunday, 3/31, around 8:00 PM eastern
time? I have a few tasks that I had to take care of, but I should get these
issues done by then.

**Comment by Simply007** [comment]
The changes look fine, but there were still some issues:
* I have submitted the pull request (https://github.com/dacdao1/kentico.github.io/pull/2) to your fork, so the merging would cause passing this continuous integration step.
* Extracted color definition to the colors scss module
* Fixed imports paths
* Add missing imports to the index.scss

Before requesting a review, please:
1. Run the website locally ([How to](https://github.com/Kentico/kentico.github.io/tree/source#-quick-start)) and fix all errors, if they are any.
2. Run the build step ([How to](https://github.com/Kentico/kentico.github.io/blob/source/README.md#build) - sorry just added to the readme) and fix all errors, if they are any.

After requesting the pull:
1. Take a look at the continuous integration status and its details in the pull request:
image and if it is failing, fix all errors if they are any.

**Pull request merged**
